config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root to: "home#index"
  resources :projects
  post 'projects/:id/file_upload', to: 'projects#upload', as: 'projects_file_upload'
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
  before_save :create_book

  validates   :user,  presence: true

  belongs_to  :user
  belongs_to  :book, dependent: :destroy

  def add_upload_file(file)
    cs_path = File.join(Rails.root,'cs.json')
    c_path = File.join(Rails.root,'c.yaml')
    hgdoc = Hgdoc::GoogleConnector.new(cs_path, c_path)

    upload = file
    filepath = Rails.root.join('/tmp', upload.original_filename)
    File.open(filepath, 'wb') do |file|
      file.write(upload.read)
    end
    
    google_filedocument_id = hgdoc.upload(filepath.to_s)
    hgdoc.download_as_html(google_filedocument_id)
  end

  private
  def create_book
    self.book = Book.new if book.nil?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_filter :authenticate_user!, only: [:index]

    def index
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def create
        project = Project.create(user: current_user)
        redirect_to root_url
    end

    def destroy
        Project.find(params[:id]).destroy
        redirect_to root_url
    end

    def upload
        project = Project.find(params[:id])
        content = project.add_upload_file(params[:document])
        render html: content.html_safe
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
  <%= button_to 'Project', projects_path, class: 'btn btn-primary' %>
  <ul>
  <% Project.where(user: current_user).each do |project| %>
    <li>
      <%= project %> <%= link_to 'Remover', project_path(project.id), method: :delete, class: 'btn btn-danger'%>
      <%= form_tag(projects_file_upload_path(project.id), multipart: true) do %>
        <%= file_field_tag 'document' %>
        <%= submit_tag %>
      <% end %>
    </li>
  <% end %>
  </ul>
<% else %>
    <%= link_to "Efetuar Login", new_user_session_path, method: :get %>
<% end %>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <%= current_user.email %></a>
  <%= link_to destroy_user_session_path, method: :delete do %>
    <span class="label label-danger">Sair</span>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SciELO EdO</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</body>
</html>